# Generated by Django 5.0.1 on 2024-01-15 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('order_direction', models.CharField(choices=[('short', 'Short')], max_length=5)),
                ('order_date_open', models.DateTimeField(verbose_name='date published')),
                ('order_date_close', models.DateTimeField(verbose_name='date published')),
                ('order_amount_open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.UUIDField(default=uuid.uuid4)),
                ('position_direction', models.CharField(choices=[('short', 'Short')], max_length=5)),
                ('position_date_open', models.DateTimeField(verbose_name='date published')),
                ('position_date_close', models.DateTimeField(verbose_name='date published')),
                ('position_amount_open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_amount_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_win', models.BooleanField()),
            ],
        ),
    ]
