# Generated by Django 5.0.1 on 2024-01-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_direction',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_direction',
            field=models.CharField(max_length=5),
        ),
    ]
